### ISSUE TITLE
toggle_wireless broken

### ISSUE THREAD

**Issue by clburlison** [clburlison/pinpoint#23]
During wireless refactor (846e200603e88488d23b3e5de2ce7e69e81098ab) I broke the `toggle_wireless` function. 

The traceback is:
```bash
Traceback (most recent call last):
  File "./pinpoint", line 888, in <module>
    main()
  File "./pinpoint", line 843, in main
    WirelessOutput = wireless().toggle_wireless('on')
  File "./pinpoint", line 585, in toggle_wireless
    iface = CWInterface.interface()
NameError: global name 'CWInterface' is not defined
```

Thanks to @hjlinde for the report

**Comment by hjlinde** [comment]
Deployed the new version and its working like a charm. :)
