### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by rfitzwater** [clburlison/pinpoint#27]
I noticed in MunkiReport that my clients weren't updating the location with pinpoint.  I ran this command manually on one machine to test: 
`sudo /Library/Application\ Support/pinpoint/bin/pinpoint -fvv`
Here is the output:

`[DEBUG]: Current LookupService is: google
[DEBUG]: Updating 'LastCheckDate' timestamp
[DEBUG]: Storing past location
[DEBUG]: Wireless interface is currently: On
[DEBUG]: Wireless interface is currently: On
[DEBUG]: No preflight script on disk
[INFO]: Scanning for wireless networks...
Traceback (most recent call last):
  File "/Library/Application Support/pinpoint/bin/pinpoint", line 888, in <module>
    main()
  File "/Library/Application Support/pinpoint/bin/pinpoint", line 858, in main
    lookup(lookup_service)
  File "/Library/Application Support/pinpoint/bin/pinpoint", line 397, in lookup
    scan = wireless().wireless_scan()
  File "/Library/Application Support/pinpoint/bin/pinpoint", line 565, in wireless_scan
    ssid_scan = FoundationPlist.readPlistFromString(ssid_scan)
  File "/Library/Application Support/pinpoint/bin/FoundationPlist/FoundationPlist.py", line 105, in readPlistFromString
    raise NSPropertyListSerializationException(error)
FoundationPlist.FoundationPlist.NSPropertyListSerializationException: Encountered unexpected EOF`

Here are the preferences I have set:
`{
    AddressLookup = 1;
    AddressLookupService = google;
    CacheDir = "/Library/Application Support/pinpoint";
    CheckWaitTime = 1800;
    DisableWireless = true;
    EnableWireless = true;
    LastCheckDate = "2017-11-15 14:59:49 +0000";
    LookupService = google;
}`

This client I tested on is running 10.12.6

**Comment by clburlison** [comment]
@rfitzwater can you please remove `/Library/Application Support/pinpoint/location.plist` and re-run pinpoint to see if that solves the error?

Is this happening on multiple machines or just one?

EOF normally means something is wrong with the formatting of that file. It's possible the python process was shut down while pinpoint was running which might have caused corruption.

**Comment by rfitzwater** [comment]
That error seems to be only on the one machine I tested. Running on the
entire lab, below are the results:

DEBUG]: Current LookupService is: google

[DEBUG]: Updating 'LastCheckDate' timestamp

[DEBUG]: Storing past location

[DEBUG]: Wireless interface is currently: On

[DEBUG]: Wireless interface is currently: On

[DEBUG]: No preflight script on disk

[INFO]: Scanning for wireless networks...

[INFO]: Scanning complete

[DEBUG]: Local wireless networks:

[{'RSSI': -49L, 'BSSID': u'b4:5d:50:cd:bb:13', 'SSID_STR': u'RUGuest'},
{'RSSI': -49L, 'BSSID': u'b4:5d:50:cd:bb:11', 'SSID_STR': u'nowires'},
{'RSSI': -56L, 'BSSID': u'84:d4:7e:78:45:33', 'SSID_STR': u'RUGuest'},
{'RSSI': -56L, 'BSSID': u'84:d4:7e:78:45:31', 'SSID_STR': u'nowires'},
{'RSSI': -60L, 'BSSID': u'c8:d7:19:4:6d:3', 'SSID_STR': u'Cisco14174'},
{'RSSI': -64L, 'BSSID': u'84:d4:7e:78:45:21', 'SSID_STR': u'nowires'},
{'RSSI': -75L, 'BSSID': u'd8:c7:c8:e8:6:99', 'SSID_STR': u'nowires'},
{'RSSI': -76L, 'BSSID': u'd8:c7:c8:e8:6:9a', 'SSID_STR': u'RUGuest'},
{'RSSI': -76L, 'BSSID': u'd8:c7:c8:e8:a:a', 'SSID_STR': u'RUGuest'},
{'RSSI': -78L, 'BSSID': u'd8:c7:c8:e8:9:ea', 'SSID_STR': u'RUGuest'},
{'RSSI': -78L, 'BSSID': u'd8:c7:c8:e8:9:e9', 'SSID_STR': u'nowires'},
{'RSSI': -83L, 'BSSID': u'20:a6:cd:de:5:33', 'SSID_STR': u'RUGuest'},
{'RSSI': -83L, 'BSSID': u'20:a6:cd:de:5:31', 'SSID_STR': u'nowires'},
{'RSSI': -86L, 'BSSID': u'c8:d7:19:4:6d:5', 'SSID_STR': u'Cisco14174'},
{'RSSI': -89L, 'BSSID': u'0:19:e3:31:3d:2c', 'SSID_STR': u'Apple Network
313d2c'}]

[INFO]: Downloading a file...

[DEBUG]: HTTP Error: 404,
https://maps.googleapis.com/maps/api/browserlocation/json?browser=firefox&wifi=mac:b4:5d:50:cd:bb:13&ssid:RUGuest&ss:-49&wifi=mac:b4:5d:50:cd:bb:11&ssid:nowires&ss:-49&wifi=mac:84:d4:7e:78:45:33&ssid:RUGuest&ss:-56&wifi=mac:84:d4:7e:78:45:31&ssid:nowires&ss:-56&wifi=mac:c8:d7:19:4:6d:3&ssid:Cisco14174&ss:-60

[DEBUG]: Couldn't read /tmp/tmpVUZrfq/tempdata

[WARNING]: Google lookup request failed

[INFO]: Doing a reverse lookup via: google

[WARNING]: Unable to determine address

[INFO]: Address is: Unable to determine address

[DEBUG]: Keep past location as we were unable to determine your current
location

[DEBUG]: Writing current run details to: /Library/Application
Support/pinpoint/location.plist

[INFO]: Run status: Unsuccessful: Google lookup request failed

[DEBUG]: No postflight script on disk

I deleted the plist file and reran and got he same results.

-Rhon

On Wed, Nov 15, 2017 at 12:22 PM, Clayton Burlison <notifications@github.com

**Comment by clburlison** [comment]
Thanks @rfitzwater. I've been able to replicate this. I will see if I can fix it.

**Comment by clburlison** [comment]
I'm pretty sure Google finally put this behind auth and requires an API key for lookups. https://developers.google.com/maps/documentation/geolocation/intro

**Comment by danner26** [comment]
Has there been any progress made here?
